### ISSUE TITLE
getting 

### ISSUE THREAD

**Issue by vinsesh** [nprint/nprintML#72]
sudo nprintml -a pcap --pcap_dir protocols/ -L labels.txt -4 -t -p 20
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.24.1 (/usr/lib/python3/dist-packages), Requirement.parse('urllib3<1.27,>=1.25.4'), {'botocore'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nprintml", line 33, in <module>
    sys.exit(load_entry_point('nprintml==1.0.3', 'console_scripts', 'nprintml')())
  File "/usr/local/bin/nprintml", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/nprintml-1.0.3-py3.7.egg/nprintml/cli.py", line 21, in <module>
    import nprintml.learn.step
  File "/usr/local/lib/python3.7/dist-packages/nprintml-1.0.3-py3.7.egg/nprintml/learn/__init__.py", line 1, in <module>
    from .automl import AutoML  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/nprintml-1.0.3-py3.7.egg/nprintml/learn/automl.py", line 13, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.7/dist-packages/matplotlib-3.3.4-py3.7-linux-x86_64.egg/matplotlib/pyplot.py", line 43, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/usr/local/lib/python3.7/dist-packages/matplotlib-3.3.4-py3.7-linux-x86_64.egg/matplotlib/figure.py", line 18, in <module>
    from matplotlib import docstring, projections
  File "/usr/local/lib/python3.7/dist-packages/matplotlib-3.3.4-py3.7-linux-x86_64.egg/matplotlib/projections/__init__.py", line 4, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/usr/local/lib/python3.7/dist-packages/matplotlib-3.3.4-py3.7-linux-x86_64.egg/mpl_toolkits/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'urllib3<1.27,>=1.25.4' distribution was not found and is required by botocore

**Comment by jesteria** [comment]
Hello @vinsesh – as best I can tell from your traceback it looks like nprintML wasn't installed correctly.

* You've attempted to install the library globally on your system **as root**. That _could_ work fine.
* But, for whatever reason this left you with an old version of `urllib3`; a dependency of the library is a later version of `urllib3`.

You may install the library however is most useful to you. But, as I said, for whatever reason, this didn't work.

You might try simply:

```sh
python -m pip install --user nprintml
```

Or much better try installing into a virtualenv.

If you like, give `pipx` a shot, also as mentioned in the README. (I'm guessing this might be a user experience you'd like!)

Regardless, good luck!
