### ISSUE TITLE
[Question]: When I run nprintml, I get the error pytz: No module named 'zoneinfo'

### ISSUE THREAD

**Issue by gtumadopt** [nprint/nprintML#94]
### What's up?

When I run nprintml, I get the error pytz: No module named 'zoneinfo'

$ nprintml -L labels.txt -a pcap --pcap_dir dataset/ -4 -u -p 10
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/nprintml", line 5, in <module>
    from nprintml.cli import execute
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nprintml/cli.py", line 16, in <module>
    from nprintml.util import NumericRangeType
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nprintml/util/__init__.py", line 1, in <module>
    from .fileformat import format_handlers  # noqa: F401
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nprintml/util/fileformat.py", line 4, in <module>
    import pandas as pd
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
pytz: No module named 'zoneinfo'

I have installed pytz.
$ python -m pip install pytz
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (2022.1)

How to solve this problem?

### Due diligence

- [X] I have read the docs

**Comment by JordanHolland** [comment]
Have you tried the docker image? Difficult to understand if this is local to your device.
